mysite/blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.hello)
]

mysite/blog2/urls.py
from django.urls import path
from . import views
app_name ='blog2'
urlpatterns = [
    path('',views.hello),
    path('article/<int:article_id>/',views.article_page,name='article_page'),
    path('edit/<int:article_id>/',views.edit_page,name='edit_page'),
    path('edit/action',views.edit_action,name='edit_action')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('blog2/',include('blog2.urls',namespace='blog2'))
]

mysite/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=32,default='Title')
    content=models.TextField(null=True)

    def  __str__(self):
        return self.title

mysite/blog2/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=32,default='Title') #max_length约束长度
    content=models.TextField(null=True)
    pub_time=models.DateTimeField(auto_now=True)

    def  __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.
def hello(request):
    # return HttpResponse('<html>hello wb</html>')
    # return render(request,'index1.html',{'hello':'hello,blog1'})
    article = models.Article.objects.get(pk=1)
    return render(request, 'index1.html', {'article': article})

mysite/blog2/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.
def hello(request):
    # return HttpResponse('<html>hello wb</html>')
    articles=models.Article.objects.all()
    return render(request,'blog2/index1.html',{'articles': articles})

def article_page(request,article_id):
    article_id=int(article_id)
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog2/article_page.html',{'article': article})

def edit_page(request,article_id):
    if str(article_id)=='0':
        return render(request, 'blog2/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog2/edit_page.html',{'article': article})


def edit_action(request):
    title=request.POST.get('title','TITLE')
    content=request.POST.get('content','CONTENT')
    article_id=request.POST.get('article_id','0')
    if article_id=='0':
        models.Article.objects.create(title=title,content=content)
        articles=models.Article.objects.all()
        return render(request,'blog2/index1.html',{'articles': articles})
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title=title
        article.content=content
        article.save()
        return render(request, 'blog2/article_page.html', {'article': article})

mysite/blog/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>{{hello}}</h1>-->
<h1>{{article.title}}</h1>
<h3>{{article.content}}</h3>
</body>
</html>

mysite/blog2/templates/blog2/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br/>
<h3>{{article.content}}</h3>
<br/><br/>
<a href="{% url 'blog2:edit_page' article.id %}">修改文章</a>
</body>
</html>

mysite/blog2/templates/blog2/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{%  url 'blog2:edit_action' %}" method="post">
    {% csrf_token%}
    {% if article %}
        <input type="hidden" name="article_id" value="{{article.id}}"/>
        <label>文章标题
            <input type="text" name="title" value="{{article.title}}"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{article.content}}"/>
        </label>
        <br/>
    {% else %}
        <input type="hidden" name="article_id" value="0"/>
        <label>文章标题
            <input type="text" name="title" />
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" />
        </label>
        <br/>
    {% endif %}
    <input type="submit" value="提交">
</form>
</body>
</html>

mysite/blog2/templates/blog2/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog2:edit_page' 0 %}">新文章</a>
</h1>>
{% for article in articles %}
    <a href="{% url 'blog2:article_page' article.id %}">{{article.title}}</a>
    <br/>
{% endfor %}
</body>
</html>